# 1. Configuración del Servidor
server.port=9091
spring.application.name=Muta New Service

# 2. Conexión a Base de Datos (PostgreSQL)
# Reemplaza 'nombre_tu_db' por el nombre real de tu base de datos
spring.datasource.url=jdbc:postgresql://maindb-dev.cgsyabvnvt3b.us-east-1.rds.amazonaws.com:5432/muta
spring.datasource.username=postgres
spring.datasource.password=aeiou123
spring.datasource.driver-class-name=org.postgresql.Driver


# Unidad de medida dinámica para la respuesta de la API
app.conversion.display-measure=${CUSTOM_MEASURE:LT}